# Generated by Django 5.2 on 2025-05-10 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csv_reader', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeereport',
            name='employee_id',
            field=models.CharField(primary_key=True, serialize=False),
        ),
    ]
