# Generated by Django 5.2 on 2025-05-10 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csv_reader', '0002_alter_employeereport_employee_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeereport',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='employeereport',
            name='employee_id',
            field=models.CharField(),
        ),
    ]
