# Generated by Django 5.2 on 2025-05-10 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csv_reader', '0003_employeereport_id_alter_employeereport_employee_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('total_employees', models.PositiveIntegerField()),
                ('total_hours_worked', models.PositiveIntegerField()),
                ('total_hours_late', models.PositiveIntegerField()),
                ('average_hours_worked', models.PositiveIntegerField()),
                ('average_hourly_rate', models.PositiveIntegerField()),
                ('files_processed', models.PositiveIntegerField()),
                ('files_names', models.CharField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
