# Generated by Django 5.1.7 on 2025-05-16 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csv_reader', '0004_report'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeereport',
            name='employee_id',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='report',
            name='files_names',
            field=models.CharField(max_length=255),
        ),
    ]
