# Generated by Django 5.2 on 2025-04-27 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tree', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Parent',
        ),
    ]
